USE GSSWEB
GO
--DECLARE @ColumnGroup
DECLARE @ColumnGroup NVARCHAR(MAX)
SELECT @ColumnGroup = COALESCE(@ColumnGroup + ',' ,'' ) + QUOTENAME(CONVERT(NVARCHAR, A.year)) 
FROM (
	SELECT DISTINCT DATEPART(YEAR,BLR.LEND_DATE) as [year]
	FROM dbo.BOOK_LEND_RECORD as BLR) AS A
GROUP BY A.year

--DECLARE @ColumnSelect
DECLARE @ColumnSelect NVARCHAR(MAX)  = ''
SELECT @ColumnSelect += COALESCE(',ISNULL(['+CONVERT(NVARCHAR, A.year) + '],0) as CNT' + CONVERT(NVARCHAR, A.year),'') 
FROM (
	SELECT DISTINCT BD.BOOK_CLASS_ID as [ClassID],BC.BOOK_CLASS_NAME as [ClassName],
	DATEPART(YEAR,BLR.LEND_DATE) as [year],COUNT(*) AS Cnt
	FROM dbo.BOOK_LEND_RECORD as BLR
	INNER JOIN dbo.BOOK_DATA as BD ON BLR.BOOK_ID=BD.BOOK_ID
	INNER JOIN dbo.BOOK_CLASS as BC ON BD.BOOK_CLASS_ID = BC.BOOK_CLASS_ID
	GROUP BY BD.BOOK_CLASS_ID,BC.BOOK_CLASS_NAME,DATEPART(YEAR,BLR.LEND_DATE)) AS A
GROUP BY A.year
--PIVOT
DECLARE @PIVOT AS NVARCHAR(MAX)
SET @PIVOT = 
   'SELECT ClassID,ClassName'+@ColumnSelect+'
	FROM
		(SELECT BD.BOOK_CLASS_ID as [ClassID],BC.BOOK_CLASS_NAME as [ClassName],
		DATEPART(YEAR,BLR.LEND_DATE) as [year],COUNT(*) AS Cnt
		FROM dbo.BOOK_LEND_RECORD as BLR
		INNER JOIN dbo.BOOK_DATA as BD ON BLR.BOOK_ID=BD.BOOK_ID
		INNER JOIN dbo.BOOK_CLASS as BC ON BD.BOOK_CLASS_ID = BC.BOOK_CLASS_ID
		GROUP BY BD.BOOK_CLASS_ID,BC.BOOK_CLASS_NAME,DATEPART(YEAR,BLR.LEND_DATE)) AS Y
	PIVOT (SUM(Cnt) FOR [year] IN ('+@ColumnGroup+')) AS pvt
	ORDER BY ClassID'
EXEC sys.sp_executesql @PIVOT;

GO
