USE GSSWEB
GO
SELECT Top 5 BLR.BOOK_ID as [BookId],BD.BOOK_NAME as [BookName],Count(*) as [Qty]
FROM dbo.BOOK_LEND_RECORD as BLR
INNER JOIN dbo.BOOK_DATA as BD
	ON BLR.BOOK_ID=BD.BOOK_ID
GROUP BY BLR.BOOK_ID,BD.BOOK_NAME
ORDER BY Qty Desc