USE GSSWEB
GO
CREATE FUNCTION dbo.getCNT (@yy nvarchar(10))  
RETURNS TABLE  
AS  
RETURN   
(  
    SELECT BD.BOOK_CLASS_ID,BC.BOOK_CLASS_NAME,count(*) as [cnt]
	FROM dbo.BOOK_LEND_RECORD as BLR
	INNER JOIN dbo.BOOK_DATA as BD ON BLR.BOOK_ID=BD.BOOK_ID
	INNER JOIN dbo.BOOK_CLASS as BC ON BD.BOOK_CLASS_ID = BC.BOOK_CLASS_ID
	WHERE DATEPART(YEAR,BLR.LEND_DATE) = @yy
	GROUP BY BD.BOOK_CLASS_ID,BC.BOOK_CLASS_NAME
); 
SELECT BC.BOOK_CLASS_ID as ClassId,BC.BOOK_CLASS_NAME as ClassName,
		CASE WHEN CNT2016.cnt IS NULL  THEN 0 ELSE CNT2016.cnt END as [CNT2016], 
		CASE WHEN CNT2017.cnt IS NULL  THEN 0 ELSE CNT2017.cnt END as [CNT2017],
		CASE WHEN CNT2018.cnt IS NULL  THEN 0 ELSE CNT2018.cnt END as [CNT2018],
		CASE WHEN CNT2019.cnt IS NULL  THEN 0 ELSE CNT2019.cnt END as [CNT2019]
FROM dbo.BOOK_CLASS as BC
LEFT JOIN dbo.getCNT('2016') as CNT2016 ON  BC.BOOK_CLASS_ID = CNT2016.BOOK_CLASS_ID
LEFT JOIN dbo.getCNT('2017') as  CNT2017 ON  BC.BOOK_CLASS_ID = CNT2017.BOOK_CLASS_ID
LEFT JOIN dbo.getCNT('2018') as  CNT2018 ON  BC.BOOK_CLASS_ID = CNT2018.BOOK_CLASS_ID
LEFT JOIN dbo.getCNT('2019') as  CNT2019 ON  BC.BOOK_CLASS_ID = CNT2019.BOOK_CLASS_ID
ORDER BY ClassId



