USE GSSWEB
GO
/*確認要刪除的條件和刪除的物件相符合*/
SELECT *
FROM dbo.BOOK_LEND_RECORD
WHERE dbo.BOOK_LEND_RECORD.BOOK_ID = '2004'


DELETE FROM dbo.BOOK_LEND_RECORD 
WHERE dbo.BOOK_LEND_RECORD.BOOK_ID = '2004'
AND  dbo.BOOK_LEND_RECORD.KEEPER_ID = '0002'
