USE GSSWEB
--宣告變數取得年份
DECLARE @ColumnGroup NVARCHAR(MAX)
SELECT @ColumnGroup = COALESCE(@ColumnGroup + ',' ,'' ) + QUOTENAME(CONVERT(NVARCHAR, A.year)) 
FROM (SELECT BD.BOOK_CLASS_ID as [ClassID],BC.BOOK_CLASS_NAME as [ClassName],
	DATEPART(YEAR,BLR.LEND_DATE) as [year],COUNT(*) AS Cnt
	FROM dbo.BOOK_LEND_RECORD as BLR
	INNER JOIN dbo.BOOK_DATA as BD ON BLR.BOOK_ID=BD.BOOK_ID
	INNER JOIN dbo.BOOK_CLASS as BC ON BD.BOOK_CLASS_ID = BC.BOOK_CLASS_ID
	GROUP BY BD.BOOK_CLASS_ID,BC.BOOK_CLASS_NAME,DATEPART(YEAR,BLR.LEND_DATE)) AS A
GROUP BY A.year
--呼叫procedures帶入年份變數
EXEC dbo.getYears @ResYears = @ColumnGroup 
GO
--建立一個procedures FOR PIVOT
ALTER PROCEDURE dbo.getYears(@ResYears AS NVARCHAR(MAX))
AS
DECLARE @PIVOT AS NVARCHAR(MAX)
SELECT @PIVOT = 'SELECT ClassID,ClassName,ISNULL([2016],0) as CNT2016,ISNULL([2017],0) as CNT2017,ISNULL([2018],0) as CNT2018,ISNULL([2019],0) as CNT2019
FROM
	(SELECT BD.BOOK_CLASS_ID as [ClassID],BC.BOOK_CLASS_NAME as [ClassName],
	DATEPART(YEAR,BLR.LEND_DATE) as [year],COUNT(*) AS Cnt
	FROM dbo.BOOK_LEND_RECORD as BLR
	INNER JOIN dbo.BOOK_DATA as BD ON BLR.BOOK_ID=BD.BOOK_ID
	INNER JOIN dbo.BOOK_CLASS as BC ON BD.BOOK_CLASS_ID = BC.BOOK_CLASS_ID
	GROUP BY BD.BOOK_CLASS_ID,BC.BOOK_CLASS_NAME,DATEPART(YEAR,BLR.LEND_DATE)) AS Y
PIVOT (SUM(Cnt) FOR [year] IN ('+@ResYears+')) AS pvt
ORDER BY ClassID'
EXEC sys.sp_executesql @PIVOT;
GO

