USE GSSWEB
GO
SELECT BD.BOOK_ID as [書本ID],CONVERT(varchar(100), BD.BOOK_BOUGHT_DATE, 111) as [購書日期],
	   CONVERT(varchar(100), BLR.LEND_DATE, 111) as [借閱日期],BC.BOOK_CLASS_ID+'-'+BC.BOOK_CLASS_NAME as [書籍類別],
	   MM.USER_ID+'-'+MM.USER_CNAME+'('+MM.USER_ENAME+')' as [借閱人],
	   CD.CODE_ID+'-'+CD.CODE_NAME as [狀態],BD.BOOK_AMOUNT as [購書金額]
FROM dbo.BOOK_DATA as BD
	INNER JOIN dbo.BOOK_LEND_RECORD as BLR ON BD.BOOK_ID = BLR.BOOK_ID
	INNER JOIN dbo.BOOK_CLASS as BC ON BD.BOOK_CLASS_ID = BC.BOOK_CLASS_ID
	INNER JOIN dbo.BOOK_CODE as CD ON BD.BOOK_STATUS = CD.CODE_ID
	INNER JOIN dbo.MEMBER_M as MM ON BLR.KEEPER_ID = MM.USER_ID
WHERE MM.USER_CNAME='李四'
ORDER BY [購書金額] DESC