USE GSSWEB
GO
WITH CntTable AS(
	SELECT BC.BOOK_CLASS_NAME as [BookClass],BD.BOOK_ID as BookId,BD.BOOK_NAME as BookName,count(*) as Cnt
	FROM dbo.BOOK_LEND_RECORD as BLR
	INNER JOIN dbo.BOOK_DATA as BD ON BLR.BOOK_ID = BD.BOOK_ID
	INNER JOIN dbo.BOOK_CLASS as BC ON BD.BOOK_CLASS_ID = BC.BOOK_CLASS_ID
	GROUP BY BC.BOOK_CLASS_NAME,BD.BOOK_ID,BD.BOOK_NAME
)
SELECT *
FROM(
	SELECT 
	  ROW_NUMBER() OVER(PARTITION BY BookClass ORDER BY Cnt desc) 
		AS Row#,CT.*
	FROM CntTable as CT) as A
WHERE Row#<=3



